[package]
name = "subping"
version = "0.1.0"
edition = "2021"

[dependencies]
ipnetwork = "0.18.0"
tokio = { version = "1.29.0", features = ["full"] }
futures = "0.3.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
